add support for Centos and RHEL

diff --git a/.scripts/defs b/.scripts/defs
--- a/.scripts/defs
+++ b/.scripts/defs
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 
 csource() {
-  if [ -r "$@" ]; then
-    . "$@"
-  fi
+    if [ -r "$@" ]; then
+        . "$@"
+    fi
 }
 
 export NVM_DIR="$HOME/.nvm"
@@ -15,11 +15,14 @@ csource /etc/os-release
 # init distro check #
 #####################
 LINUX_VERSION_NAME="$NAME"
+IS_ARCH_BASED=false
 IS_ARCH=false
 IS_ARCO=false
 IS_MANJARO=false
+IS_RH_BASED=false
 IS_FEDORA=false
 IS_RHEL=false
+IS_CENTOS=false
 
 SCRIPTS="$HOME/.scripts"
 
@@ -30,110 +33,127 @@ ERROR_PAKAGE_UNINST=
 ERROR_PAKAGE_INST=
 
 if [ "$LINUX_VERSION_NAME" = "Arch" ]; then
-	IS_ARCH=true
+    IS_ARCH=true
+    IS_ARCH_BASED=true
 fi
 
 if [ "$LINUX_VERSION_NAME" = "ArcoLinux" ]; then
-	IS_ARCO=true
+    IS_ARCO=true
+    IS_ARCH_BASED=true
 fi
 
 if [ "$LINUX_VERSION_NAME" = "ManjaroLinux" ]; then
-	IS_MANJARO=true
+    IS_MANJARO=true
+    IS_ARCH_BASED=true
 fi
 
 if [ "$LINUX_VERSION_NAME" = "Fedora Linux" ]; then
-	IS_FEDORA=true
+    IS_FEDORA=true
+    IS_RH_BASED=true
 fi
 
 if [ "$LINUX_VERSION_NAME" = "RHEL" ]; then
-	IS_RHEL=true
+    IS_RHEL=true
+    IS_RH_BASED=true
 fi
 
-if [ "$IS_FEDORA" = true ]; then
-    PACTOOL=dnf
+if [ "$LINUX_VERSION_NAME" = "CentOS Stream" ]; then
+    IS_CENTOS=true
+    IS_RH_BASED=true
+fi
+
+if [ $IS_ARCH_BASED = true ]; then
+    PACTOOL=yum
 else
-	PACTOOL=pacman
+    PACTOOL=pacman
+    if [ -x "$(command -v yay)" ]; then
+        export PACTOOL=yay
+    fi
+    if [ -x "$(command -v paru)" ]; then
+        export PACTOOL=paru
+    fi
 fi
 
-if [ -x "$(command -v yay)" ]; then
-  export PACTOOL=yay
-fi
-if [ -x "$(command -v paru)" ]; then
-  export PACTOOL=paru
-fi
 
 PACKER="$PACTOOL"
 MAKEFLAGS="-j$(nproc)"
 
-if [ "$IS_FEDORA" = true ]; then
-	PACKER_ALL="--verbose $@" 
+if [ "$IS_RH_BASED" = true ]; then
+    PACKER_ALL="--verbose $@"
 else
-	PACKER_ALL="--color always --needed --overwrite \* $@" 
+    PACKER_ALL="--color always --needed --overwrite \* $@"
 fi
-		
-# echo "Linux Version..: $LINUX_VERSION_NAME"
-# echo "IsArch.........: $IS_ARCH"
-# echo "IsArco.........: $IS_ARCO"
-# echo "IsManjaro......: $IS_MANJARO"
-# echo "IsFedora.......: $IS_FEDORA"
-# echo "IsRHEL.........: $IS_RHEL"
-# echo "Package Manager: $PACTOOL"
-# echo "AUR Manager....: $PACKER"
-# echo "Packer Params..: $PACKER_ALL"
+
+echo "Linux Version..: $LINUX_VERSION_NAME"
+echo "Based on ArchLinux.: $IS_ARCH_BASED"
+echo "Based on RHEL......: $IS_RH_BASED"
+echo "IsArch.............: $IS_ARCH"
+echo "IsArco.............: $IS_ARCO"
+echo "IsManjaro..........: $IS_MANJARO"
+echo "IsFedora...........: $IS_FEDORA"
+echo "IsRHEL.............: $IS_RHEL"
+echo "IsCentOS...........: $IS_CENTOS"
+echo "Package Manager....: $PACTOOL"
+echo "AUR Manager........: $PACKER"
+echo "Packer Params......: $PACKER_ALL"
 
 initInstall() {
-	INSTALL_SCRIPT=$1
-	echo "Step: init Install '$INSTALL_SCRIPT'"
-	sudo rm /var/lib/pacman/db.lck 2&> /dev/null	
+    INSTALL_SCRIPT=$1
+    echo "Step: init Install '$INSTALL_SCRIPT'"
+    sudo rm /var/lib/pacman/db.lck 2&> /dev/null
 }
 
 install() {
     PAKAGE_INST="${PAKAGE_INST} $1"
     
     if [ $DEBUG = true ]; then
-		if [ $IS_FEDORA = true ]; then
-			eval "sudo $PACKER install $PACKER_ALL $1"
-		else
-			eval "$PACKER -S $PACKER_ALL $1"
-		fi
-		
-	    retVal=$?
-	    if [ $retVal -ne 0 ]; then
-	        echo "error on install: $1"
-			ERROR_PAKAGE_INST="${ERROR_PAKAGE_INST} $1"        
-	    fi
+        if [ $IS_RH_BASED = true ]; then
+            eval "sudo $PACKER install $PACKER_ALL $1"
+        else
+            eval "$PACKER -S $PACKER_ALL $1"
+        fi
+        
+        retVal=$?
+        if [ $retVal -ne 0 ]; then
+            echo "error on install: $1"
+            ERROR_PAKAGE_INST="${ERROR_PAKAGE_INST} $1"
+        fi
     fi
 }
 
 fullInstall() {
-	echo "Step: full Install"
-	if [ $DEBUG != true -a "$PAKAGE_INST" != "" ]; then
-		if [ $IS_FEDORA = true ]; then
-			eval "sudo $PACKER install $PACKER_ALL $PAKAGE_INST"
-		else
-			eval "$PACKER -S $PACKER_ALL $PAKAGE_INST"
-		fi
-		errorCheck "install packages"
-	fi
+    echo "Step: full Install"
+    if [ $DEBUG != true -a "$PAKAGE_INST" != "" ]; then
+        if [ $IS_RH_BASED = true ]; then
+            eval "sudo $PACKER install $PACKER_ALL $PAKAGE_INST"
+        else
+            eval "$PACKER -S $PACKER_ALL $PAKAGE_INST"
+        fi
+        errorCheck "install packages"
+    fi
 }
 
 uninstall() {
     PAKAGE_UNINST="${PAKAGE_UNINST} $1"
-
+    
     eval "$PACKER -R $1"
     
     retVal=$?
     if [ $retVal -ne 0 ]; then
         echo "error on uninstall: $1"
-		ERROR_PAKAGE_UNINST="${ERROR_PAKAGE_UNINST} $1"        
+        ERROR_PAKAGE_UNINST="${ERROR_PAKAGE_UNINST} $1"
     fi
 }
 
 fullUninstall() {
-	echo "Step: full Uninstall"
-	if [ $DEBUG != true -a "$PAKAGE_UNINST" != "" ]; then
-		eval "$PACKER -R --noconfirm $PAKAGE_UNINST"
-	fi
+    echo "Step: full Uninstall"
+    if [ $DEBUG != true -a "$PAKAGE_UNINST" != "" ]; then
+        if [ $IS_RH_BASED = true ]; then
+            eval "sudo $PACKER remove $PAKAGE_UNINST"
+        else
+            eval "$PACKER -R --noconfirm $PAKAGE_UNINST"
+        fi
+    fi
 }
 
 errorCheck() {
@@ -145,28 +165,28 @@ errorCheck() {
 }
 
 finish() {
-	echo "Step: finish Install"
-
-	if [ "$ERROR_PAKAGE_UNINST" = "" ]; then
-		echo 'No Errors on Uninstall'
-	else
-		echo "Error on Uninstall: ${ERROR_PAKAGE_UNINST}"
-		echo "Error on Uninstall: ${ERROR_PAKAGE_UNINST}" >> error_uninstall.txt
-	fi	
-
-	if [ "$ERROR_PAKAGE_INST" = "" ]; then
-		echo 'No Errors on Install'
-	else
-		echo "Error on Install: ${ERROR_PAKAGE_INST}"
-		echo "Error on Install: ${ERROR_PAKAGE_INST}" >> error_install.txt
-	fi	
+    echo "Step: finish Install"
+    
+    if [ "$ERROR_PAKAGE_UNINST" = "" ]; then
+        echo 'No Errors on Uninstall'
+    else
+        echo "Error on Uninstall: ${ERROR_PAKAGE_UNINST}"
+        echo "Error on Uninstall: ${ERROR_PAKAGE_UNINST}" >> error_uninstall.txt
+    fi
+    
+    if [ "$ERROR_PAKAGE_INST" = "" ]; then
+        echo 'No Errors on Install'
+    else
+        echo "Error on Install: ${ERROR_PAKAGE_INST}"
+        echo "Error on Install: ${ERROR_PAKAGE_INST}" >> error_install.txt
+    fi
 }
 
 run() {
     if command -v $1 &>/dev/null; then
         #pgrep -u "$USER" -fx "$1" >/dev/null || ($@) &
         if ! pgrep "$1"; then
-            $@ &
+            "$@" &
         fi
         notify-send -t 10000 "AUTOSTART" "Kommando:\n'$1'"
     else
@@ -177,31 +197,31 @@ run() {
 restart() {
     killall "$1"
     sleep 1
-    run $@
+    run "$@"
 }
 
 # # ex = EXtractor for all kinds of archives
 # # usage: ex <file>
 expand() {
-  if [ -f $1 ]; then
-    case $1 in
-    *.tar.bz2) tar xjf $1 ;;
-    *.tar.gz) tar xzf $1 ;;
-    *.bz2) bunzip2 $1 ;;
-    *.rar) unrar x $1 ;;
-    *.gz) gunzip $1 ;;
-    *.tar) tar xf $1 ;;
-    *.tbz2) tar xjf $1 ;;
-    *.tgz) tar xzf $1 ;;
-    *.zip) unzip $1 ;;
-    *.Z) uncompress $1 ;;
-    *.7z) 7z x $1 ;;
-    *.deb) ar x $1 ;;
-    *.tar.xz) tar xf $1 ;;
-    *.tar.zst) unzstd $1 ;;
-    *) echo "'$1' cannot be extracted via ex()" ;;
-    esac
-  else
-    echo "'$1' is not a valid file"
-  fi
+    if [ -f $1 ]; then
+        case $1 in
+            *.tar.bz2) tar xjf $1 ;;
+            *.tar.gz) tar xzf $1 ;;
+            *.bz2) bunzip2 $1 ;;
+            *.rar) unrar x $1 ;;
+            *.gz) gunzip $1 ;;
+            *.tar) tar xf $1 ;;
+            *.tbz2) tar xjf $1 ;;
+            *.tgz) tar xzf $1 ;;
+            *.zip) unzip $1 ;;
+            *.Z) uncompress $1 ;;
+            *.7z) 7z x $1 ;;
+            *.deb) ar x $1 ;;
+            *.tar.xz) tar xf $1 ;;
+            *.tar.zst) unzstd $1 ;;
+            *) echo "'$1' cannot be extracted via ex()" ;;
+        esac
+    else
+        echo "'$1' is not a valid file"
+    fi
 }
